# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: vaquita_db
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tharadas@2003
      # POSTGRES_DB: postgres

    # image: postgres:13-alpine
    # environment: 
    #   - POSTGRES_DB=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres